<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- EXE name -->
    <AssemblyName>AxiLANswerApi</AssemblyName>

    <!-- Versioning -->
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>

    <!-- Windows file properties -->
    <Title>AxiLANswerApi API</Title>
    <Product>AxiLANswerApi</Product>
    <Description>Backend API for AxiLANswerApi network visualization</Description>
    <Company>Axians</Company>
    <Authors>Theodor Wase and Walter Almgren</Authors>

  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

</Project>
