<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- EXE name -->
    <AssemblyName>AxiLANswerApi</AssemblyName>

    <!-- Versioning -->
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>

    <!-- Windows file properties -->
    <Title>AxiLANswer API</Title>
    <Product>AxiLANswer</Product>
    <Description>Backend API for AxiLANswer network visualization</Description>
    <Company>Axians</Company>
    <Authors>Theodor Wase and Walter Almgren</Authors>

    <UserSecretsId>9a99dfb5-154a-4831-90c9-3b0059ac3893</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

</Project>
